"""Vision-model reward for an 8-frame SVG animation generated by Pi."""

from __future__ import annotations

import base64
import json
import logging
import os
import re
import shutil
import tempfile
import urllib.request
import uuid
import xml.etree.ElementTree as ET
from pathlib import Path, PurePosixPath
from typing import Any

REQUIRED_FILES = tuple(f"frame-{index:02d}.svg" for index in range(8))
RUBRIC_COUNTS = {
    "svg_quality": 8,
    "motion_continuity": 8,
    "prompt_alignment": 8,
    "visual_aesthetics": 8,
}
logger = logging.getLogger(__name__)


def reward_fn(record) -> float:
    workspace = _record_workspace(record)
    try:
        files = _extract_workspace_files(workspace) if workspace is not None else _extract_files(record)
        if set(files) != set(REQUIRED_FILES):
            logger.warning("Pi animation reward missing required frames: found=%s workspace=%s", sorted(files), workspace)
            return -1.0
        rendered_pngs = _render_svg_frames(files, _sample_id(record))
        svg_quality, motion, alignment, aesthetics = _judge(
            rendered_pngs,
            files,
            str(record.source_record.get("design_prompt") or record.prompt),
        )
    except Exception as exc:
        logger.warning("Pi animation reward evaluation failed: %s", exc, exc_info=True)
        return -1.0
    finally:
        if workspace is not None:
            shutil.rmtree(workspace, ignore_errors=True)
    turns = max(sum(event.type == "request" for event in record.trace), 1)
    efficiency = 1.0 / turns
    judged_score = _calibrate_judge_scores(svg_quality, motion, alignment, aesthetics)
    return max(-1.0, min(1.0, 0.95 * judged_score + 0.05 * efficiency))


def _calibrate_judge_scores(
    svg_quality: float,
    motion: float,
    alignment: float,
    aesthetics: float,
) -> float:
    scores = (svg_quality, motion, alignment, aesthetics)
    weighted = (
        0.20 * svg_quality
        + 0.30 * motion
        + 0.25 * alignment
        + 0.25 * aesthetics
    )
    # A severe weakness should remain visible instead of being hidden by three
    # generous category scores. Five is the neutral professional threshold.
    adjusted = weighted - 0.25 * (weighted - min(scores))
    return max(-1.0, min(1.0, (adjusted - 5.0) / 5.0))


def _record_workspace(record) -> Path | None:
    source = getattr(record, "source_record", None)
    raw = source.get("_pi_workspace") if isinstance(source, dict) else None
    if not raw:
        return None
    workspace = Path(str(raw)).resolve()
    temp_root = Path(tempfile.gettempdir()).resolve()
    if workspace.parent != temp_root or not workspace.name.startswith("areno-coding-"):
        raise RuntimeError(f"refusing unsafe Pi workspace path: {workspace}")
    return workspace


def _extract_workspace_files(workspace: Path) -> dict[str, str]:
    files: dict[str, str] = {}
    for name in REQUIRED_FILES:
        path = workspace / name
        if not path.is_file() or path.stat().st_size > 1_000_000:
            continue
        files[name] = path.read_text(encoding="utf-8")
    return files


def _extract_files(record) -> dict[str, str]:
    files: dict[str, str] = {}
    for call in record.tool_calls:
        if call.get("name") != "write":
            continue
        args = call.get("arguments")
        if isinstance(args, str):
            try:
                args = json.loads(args)
            except json.JSONDecodeError:
                continue
        if not isinstance(args, dict):
            continue
        path = str(args.get("path") or "").replace("\\", "/")
        parsed_path = PurePosixPath(path)
        name = parsed_path.name
        content = args.get("content")
        is_direct_path = parsed_path.is_absolute() or parsed_path.parent == PurePosixPath(".")
        if name in REQUIRED_FILES and is_direct_path and isinstance(content, str) and len(content) <= 1_000_000:
            files[name] = content
    return files


def _render_svg_frames(files: dict[str, str], sample_id: str = "sample") -> list[bytes]:
    try:
        import cairosvg
    except ImportError as exc:
        raise RuntimeError(
            "SVG animation reward requires CairoSVG; install examples/areno/requirements.txt"
        ) from exc
    pngs = []
    for name in REQUIRED_FILES:
        source = files[name]
        _validate_svg(source, name)
        png = cairosvg.svg2png(
            bytestring=source.encode("utf-8"),
            output_width=512,
            output_height=512,
        )
        if not png.startswith(b"\x89PNG\r\n\x1a\n"):
            raise RuntimeError(f"CairoSVG output for {name} is not a valid PNG")
        pngs.append(png)
    _save_animation_sample(sample_id, files, pngs)
    return pngs


def _validate_svg(source: str, name: str) -> None:
    try:
        root = ET.fromstring(source)
    except ET.ParseError as exc:
        raise ValueError(f"invalid SVG in {name}: {exc}") from exc
    if root.tag.rsplit("}", 1)[-1].lower() != "svg":
        raise ValueError(f"{name} root element must be svg")
    if re.split(r"[ ,]+", root.attrib.get("viewBox", "").strip()) != ["0", "0", "512", "512"]:
        raise ValueError(f"{name} must use viewBox='0 0 512 512'")
    forbidden_tags = {"animate", "animatemotion", "animatetransform", "foreignobject", "image", "script", "set"}
    tags = {element.tag.rsplit("}", 1)[-1].lower() for element in root.iter()}
    lowered = source.lower()
    unsafe_reference = re.search(r"(?:href|src)\s*=\s*['\"]\s*(?:data:|file:|https?:|//)", lowered)
    if tags & forbidden_tags or unsafe_reference or "url(" in lowered:
        raise ValueError(f"{name} must be a static self-contained vector SVG")


def _sample_id(record: Any) -> str:
    source = getattr(record, "source_record", {})
    raw = source.get("id") if isinstance(source, dict) else None
    return re.sub(r"[^A-Za-z0-9_.-]+", "-", str(raw or "sample")).strip("-.") or "sample"


def _save_animation_sample(sample_id: str, files: dict[str, str], pngs: list[bytes]) -> None:
    output = Path("/tmp/areno_animation")
    output.mkdir(parents=True, exist_ok=True)
    stem = f"{sample_id}-{os.getpid()}-{uuid.uuid4().hex[:8]}"
    sample_dir = output / stem
    sample_dir.mkdir()
    for index, name in enumerate(REQUIRED_FILES):
        (sample_dir / name).write_text(files[name], encoding="utf-8")
        (sample_dir / f"frame-{index:02d}.png").write_bytes(pngs[index])


def _judge(pngs: list[bytes], files: dict[str, str], prompt: str) -> tuple[float, float, float, float]:
    base_url = _required_env("PI_ARENO_JUDGE_BASE_URL").rstrip("/")
    api_key = _required_env("PI_ARENO_JUDGE_API_KEY")
    model = _required_env("PI_ARENO_JUDGE_MODEL")
    endpoint = base_url if base_url.endswith("/chat/completions") else f"{base_url}/chat/completions"
    if len(pngs) != 8 or any(not png.startswith(b"\x89PNG\r\n\x1a\n") for png in pngs):
        raise ValueError("vision judge requires exactly 8 valid PNG frames")
    source = "\n\n".join(
        f"--- {name} ---\n{files[name][:100_000]}" for name in REQUIRED_FILES
    )
    rubric = (
        "Act as a strict senior motion designer and SVG engineer. The 8 supplied images are consecutive frames 00-07 "
        "of a one-second animation at 8 FPS and must be judged in exactly that order against the prompt. Do not reward "
        "effort or mere file presence. Score every numbered checklist item independently from 0 to 10. Return "
        'JSON only with four arrays named "svg_quality", "motion_continuity", "prompt_alignment", and '
        '"visual_aesthetics". Every array must contain exactly 8 numeric scores, in the same '
        "order as the numbered checklist items. Do not return category totals, prose, explanations, or extra fields.\n\n"
        "SCORING STANDARD: 5 means minimally acceptable but visibly ordinary or incomplete; 6 means competent with "
        "several clear weaknesses; 7 means strong and usable but still has noticeable deficiencies; 8 means polished, "
        "complete, and professional with only minor issues; 9 means exceptional and highly specific with virtually no "
        "meaningful defect; 10 is reserved for outstanding work that could ship unchanged. Most animations should "
        "score between 3 and 7. Use the full range and do not cluster scores near 8. Any missing requested interaction, "
        "broken control, major overflow, overlap, inaccessible essential flow, generic template treatment, or substantial "
        "brief mismatch must cap affected items at 5. Frames that merely render without coherent motion "
        "must not score above 6.\n\n"
        "SVG QUALITY: (1) valid clean SVG structure; (2) self-contained vector construction; (3) consistent 512x512 "
        "viewBox; (4) stable element identities and geometry across frames; (5) efficient paths and grouping; (6) no "
        "accidental clipping; (7) crisp rasterization; (8) deliberate reusable visual system.\n\n"
        "MOTION CONTINUITY: (1) clear change from frame 00 to 07; (2) smooth spatial interpolation; (3) smooth scale and "
        "rotation; (4) smooth color and opacity transitions; (5) consistent object persistence; (6) readable timing and "
        "easing; (7) convincing anticipation/follow-through where relevant; (8) a complete one-second action or seamless "
        "loop rather than disconnected stills. Static, duplicated, shuffled, or abruptly jumping frames score at most 3.\n\n"
        "PROMPT ALIGNMENT: (1) correct subject; (2) correct action; (3) requested narrative progression; (4) requested "
        "palette; (5) requested style; (6) required objects and details; (7) appropriate composition; (8) recognizable "
        "domain specificity rather than a generic animation.\n\n"
        "VISUAL AESTHETICS: (1) hierarchy; (2) composition; (3) color harmony; (4) shape and line quality; (5) depth and "
        "contrast; (6) consistency across all frames; (7) originality and specificity; (8) professional polish without "
        "overlap, clipping, noise, placeholder text, or arbitrary decoration.\n\n"
        "Before assigning scores, identify concrete defects internally and lower every affected checklist item. Apply all "
        "stated caps to the relevant item scores. Do not mention that analysis in the response; output only the required "
        "JSON object containing the four score arrays.\n\n"
        f"DESIGN BRIEF:\n{prompt}\n\nSOURCE FILES:\n{source}"
    )
    image_content = [{"type": "text", "text": rubric}]
    for index, png in enumerate(pngs):
        image_content.extend([
            {"type": "text", "text": f"Frame {index:02d} of 07"},
            {"type": "image_url", "image_url": {
                "url": f"data:image/png;base64,{base64.b64encode(png).decode('ascii')}"
            }},
        ])
    payload = {
        "model": model,
        "temperature": 0,
        "response_format": {"type": "json_object"},
        "messages": [{"role": "user", "content": image_content}],
    }
    request = urllib.request.Request(
        endpoint,
        data=json.dumps(payload).encode("utf-8"),
        headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"},
        method="POST",
    )
    with urllib.request.urlopen(request, timeout=120) as response:
        body = json.loads(response.read().decode("utf-8"))
    content = body["choices"][0]["message"]["content"]
    match = re.search(r"\{[\s\S]*\}", content)
    scores = json.loads(match.group(0) if match else content)
    return (
        _rubric_mean(scores, "svg_quality"),
        _rubric_mean(scores, "motion_continuity"),
        _rubric_mean(scores, "prompt_alignment"),
        _rubric_mean(scores, "visual_aesthetics"),
    )


def _rubric_mean(scores: Any, name: str) -> float:
    if not isinstance(scores, dict):
        raise ValueError("judge response must be a JSON object")
    values = scores.get(name)
    expected = RUBRIC_COUNTS[name]
    if not isinstance(values, list) or len(values) != expected:
        raise ValueError(f"judge field {name!r} must contain exactly {expected} scores")
    return sum(_bounded(value) for value in values) / expected


def _bounded(value: Any) -> float:
    return max(0.0, min(10.0, float(value)))


def _required_env(name: str) -> str:
    value = os.environ.get(name)
    if not value:
        raise RuntimeError(f"missing required environment variable: {name}")
    return value
